// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.857
package forms

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/aandrku/portfolio-v2/pkg/view/components/common"
import "os"

func UpdateAboutDescription(html, markdown string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div id=\"update-about-description-form\" class=\"fixed inset-0 z-50 bg-black/70 flex items-center justify-center\"><form class=\"bg-zinc-800 border border-zinc-700 shadow-lg shadow-black/40 rounded-xl w-full h-full p-6 flex flex-col space-y-4 overflow-hidden\"><div class=\"flex justify-between items-center border-b border-zinc-700 pb-2\"><h2 class=\"text-lg text-zinc-300\">Your Title Here</h2><button class=\"text-zinc-400 hover:text-zinc-100 text-sm\" hx-post=\"/admin/about/update-description\" hx-target=\"#update-about-description-form\" hx-swap=\"delete\">Save</button> <button type=\"button\" class=\"text-zinc-400 hover:text-zinc-100 text-sm\" hx-get=\"/delete\" hx-target=\"#update-about-description-form\" hx-swap=\"delete\">Close</button></div><div class=\"flex-1 overflow-auto\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = common.MarkdownEditor(html, markdown).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div></form></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func UpdateAvatar(files []os.FileInfo) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<div id=\"update-avatar-form-overlay\" class=\"fixed inset-0 z-50 bg-black/60 flex items-center justify-center\"><div class=\"bg-zinc-800 border border-zinc-700 shadow-lg shadow-black/40 rounded-xl w-full max-w-md p-6 space-y-6 relative\"><div class=\"absolute -top-4 left-6 bg-zinc-900 text-zinc-300 text-lg px-3 py-1 rounded-md border border-zinc-700\">Update Avatar</div><form hx-post=\"/admin/about/update-avatar\" hx-target=\"#update-avatar-form-overlay\" hx-swap=\"delete\" class=\"space-y-4\"><div class=\"flex flex-col\"><label for=\"avatar\" class=\"text-zinc-300 mb-1\">Choose Avatar</label> <select id=\"avatar\" name=\"avatar\" required class=\"bg-zinc-900 border border-zinc-700 text-zinc-100 px-3 py-2 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500\"><option value=\"\">-- Select avatar image --</option> ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, f := range files {
			templ_7745c5c3_Err = updateAvatarOption(f).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</select></div><div class=\"flex justify-end gap-3 pt-4\"><button type=\"button\" class=\"text-zinc-400 hover:text-zinc-100\" hx-get=\"/delete\" hx-target=\"#update-avatar-form-overlay\" hx-swap=\"delete\">Cancel</button> <button type=\"submit\" class=\"bg-indigo-600 hover:bg-indigo-700 text-white px-4 py-2 rounded-md font-medium\">Save</button></div></form></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func updateAvatarOption(file os.FileInfo) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<option value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(file.Name())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `pkg/view/components/forms/about_widget_forms.templ`, Line: 70, Col: 29}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(file.Name())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `pkg/view/components/forms/about_widget_forms.templ`, Line: 70, Col: 43}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</option>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func UpdateName() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var6 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var6 == nil {
			templ_7745c5c3_Var6 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "<div id=\"update-name-form-overlay\" class=\"fixed inset-0 z-50 bg-black/60 flex items-center justify-center\"><!-- Modal Dialog --><div class=\"bg-zinc-800 border border-zinc-700 shadow-lg shadow-black/40 rounded-xl w-full max-w-md p-6 space-y-6 relative\"><div class=\"absolute -top-4 left-6 bg-zinc-900 text-zinc-300 text-lg px-3 py-1 rounded-md border border-zinc-700\">Update Name</div><!-- Form --><form hx-post=\"/admin/about/update-name\" hx-target=\"#update-name-form-overlay\" hx-swap=\"delete\" class=\"space-y-4\"><div class=\"flex flex-col\"><label for=\"name\" class=\"text-zinc-300 mb-1\">New Name</label> <input id=\"name\" name=\"name\" type=\"text\" required class=\"bg-zinc-900 border border-zinc-700 text-zinc-100 px-3 py-2 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500\"></div><div class=\"flex justify-end gap-3 pt-4\"><button type=\"button\" class=\"text-zinc-400 hover:text-zinc-100\" hx-get=\"/delete\" hx-target=\"#update-name-form-overlay\" hx-swap=\"delete\">Cancel</button> <button type=\"submit\" class=\"bg-indigo-600 hover:bg-indigo-700 text-white px-4 py-2 rounded-md font-medium\">Save</button></div></form></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func UpdateShortDescForm() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var7 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var7 == nil {
			templ_7745c5c3_Var7 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "<div id=\"update-short-desc-form-overlay\" class=\"fixed inset-0 z-50 bg-black/60 flex items-center justify-center\"><!-- Modal Dialog --><div class=\"bg-zinc-800 border border-zinc-700 shadow-lg shadow-black/40 rounded-xl w-full max-w-md p-6 space-y-6 relative\"><div class=\"absolute -top-4 left-6 bg-zinc-900 text-zinc-300 text-lg px-3 py-1 rounded-md border border-zinc-700\">Update Short Description</div><!-- Form --><form hx-post=\"/admin/about/update-short-desc\" hx-target=\"#update-short-desc-form-overlay\" hx-swap=\"delete\" class=\"space-y-4\"><div class=\"flex flex-col\"><label for=\"short-desc\" class=\"text-zinc-300 mb-1\">New Short Description</label> <input id=\"short-desc\" name=\"short-desc\" type=\"text\" required class=\"bg-zinc-900 border border-zinc-700 text-zinc-100 px-3 py-2 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500\"></div><div class=\"flex justify-end gap-3 pt-4\"><button type=\"button\" class=\"text-zinc-400 hover:text-zinc-100\" hx-get=\"/delete\" hx-target=\"#update-short-desc-form-overlay\" hx-swap=\"delete\">Cancel</button> <button type=\"submit\" class=\"bg-indigo-600 hover:bg-indigo-700 text-white px-4 py-2 rounded-md font-medium\">Save</button></div></form></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
