// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.857
package forms

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func UploadAsset() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div id=\"upload-form-overlay\" class=\"fixed inset-0 z-50 bg-black/60 flex items-center justify-center\"><!-- Modal Dialog --><div class=\"bg-zinc-800 border border-zinc-700 shadow-lg shadow-black/40 rounded-xl w-full max-w-md p-6 space-y-6 relative\"><div class=\"absolute -top-4 left-6 bg-zinc-900 text-zinc-300 text-lg px-3 py-1 rounded-md border border-zinc-700\">Upload File</div><!-- Form --><form hx-post=\"/admin/upload\" hx-encoding=\"multipart/form-data\" hx-swap=\"delete\" hx-target=\"#upload-form-overlay\" class=\"space-y-4\"><div class=\"flex flex-col\"><label for=\"filename\" class=\"text-zinc-300 mb-1\">File Name</label> <input id=\"filename\" name=\"filename\" type=\"text\" required class=\"bg-zinc-900 border border-zinc-700 text-zinc-100 px-3 py-2 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500\"></div><div class=\"flex flex-col\"><label for=\"file\" class=\"text-zinc-300 mb-1\">Choose File</label> <input id=\"file\" name=\"file\" type=\"file\" required class=\"text-zinc-100 file:mr-4 file:py-2 file:px-4 file:rounded-md file:border-0 file:text-sm file:font-semibold file:bg-indigo-600 hover:file:bg-indigo-700\"></div><div class=\"flex justify-end gap-3 pt-4\"><button type=\"button\" class=\"text-zinc-400 hover:text-zinc-100\" hx-get=\"/delete\" hx-target=\"#upload-form-overlay\" hx-swap=\"delete\">Cancel</button> <button type=\"submit\" class=\"bg-indigo-600 hover:bg-indigo-700 text-white px-4 py-2 rounded-md font-medium\">Upload</button></div></form></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func DeleteUploadConfirmationForm(fileName string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div id=\"confirm-delete-overlay\" class=\"fixed inset-0 z-50 bg-black/60 flex items-center justify-center\"><div class=\"bg-zinc-800 border border-zinc-700 shadow-lg shadow-black/40 rounded-xl w-full max-w-sm p-6 space-y-6 relative\"><div class=\"absolute -top-4 left-6 bg-zinc-900 text-zinc-300 text-lg px-3 py-1 rounded-md border border-zinc-700\">Confirm Deletion</div><div class=\"text-zinc-300\">Are you sure you want to delete <span class=\"text-red-400 font-semibold\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(fileName)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `pkg/view/components/forms/uploads_widget_forms.templ`, Line: 46, Col: 86}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</span>?</div><div class=\"flex justify-end gap-3 pt-2\"><button type=\"button\" class=\"text-zinc-400 hover:text-zinc-100\" hx-get=\"/delete\" hx-target=\"#confirm-delete-overlay\" hx-swap=\"delete\">Cancel</button> <button class=\"bg-red-700 hover:bg-red-800 text-white px-4 py-2 rounded-md font-medium\" hx-delete=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs("/admin/upload/" + fileName)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `pkg/view/components/forms/uploads_widget_forms.templ`, Line: 56, Col: 41}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\" hx-target=\"#confirm-delete-overlay\" hx-swap=\"delete\">Yes, Delete</button></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
