name: Deploy

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4


    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.2'

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install npm dependencies
      run: npm install
      working-directory: .


    - name: Build
      run: make build

    - name: Remove old server files
      uses: appleboy/ssh-action@v1.2.2
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_USER_PASSWORD }}
        script: |
          cd /home/${{ secrets.SERVER_USER }}/server
          rm main
          rm -rf assets

    - name: Copy binary to server
      uses: appleboy/scp-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}         
        username: ${{ secrets.SERVER_USER }}     
        password: ${{ secrets.SERVER_USER_PASSWORD }}  
        source: "./main"                         
        target: "/home/${{ secrets.SERVER_USER }}/server" 


    - name: Copy assets to server
      uses: appleboy/scp-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}         
        username: ${{ secrets.SERVER_USER }}     
        password: ${{ secrets.SERVER_USER_PASSWORD }}  
        source: "./assets"                         
        target: "/home/${{ secrets.SERVER_USER }}/server" 
        recursive: true                          



